name: Simple Asset Size Reporter

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2-beta
      with:
        fetch-depth: 0
    - run: yarn install
    - uses: chrysanthos/simple-asset-size-reporter@1.0.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        files: '["website/build/main*js", "website/build/styles*css", "website/build/index.html", "website/build/blog/**/introducing-docusaurus/*", "website/build/docs/introduction/index.html"]'
        with-same: 'false'
        build-assets: 'yarn build:v2'
